# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfdKXkTPQNA6g_O8M3FvmVpB4RpDsyvz

# import libraries
"""

#import libraries
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# Read data"""

#reading file
df=pd.read_csv('weather.csv')
df.head(94)

#Removing whitespace in Acres and Fires
df['Fires']=df['Fires'].str.replace(' ','')
df['Acres']=df['Acres'].str.replace('\s+', '', regex=True).astype(str)

#Given Acre and Fire values are not Integer,So Converting it into integer for further analysis
df['Acres']=df['Acres'].astype(int)
df['Fires']=df['Fires'].astype(int)

"""# Correlation between Acres and Fires column"""

#Correlation between Fires and Acres
col1=df['Fires']
col2=df['Acres']
core=col1.corr(col2)
print(core)

"""# Finding Moving Average"""

#finding moving average
df_fire = pd.DataFrame(df.Fires)
df['MA_fires']=df['Fires'].rolling(5).mean()
df['MA_acres']=df['Acres'].rolling(5).mean()
df.head(94)

"""# relation plot"""

#Relation plot from 1987 to 2019
start_date=1987
end_date=2019   
mask=(df['Year']>=start_date)&(df['Year']<=end_date)
df=df.loc[mask]

plt.figure(figsize=(30,10))
plt.scatter(x=df['Fires'],y=df['Acres'],s=120)
plt.xlabel("Fire",fontsize=20)
plt.ylabel("Acres",fontsize=20)